
Initial On Course:
  - {points: 10, all: {cm_BB: 37}}
RI 1 Never Started (and is bad):
  - {points: 10, all: {cm_P: 20}}
Nothing to DRI:
  - {points: -10, all: {cm_P: "", cm_TT: 15}}
  - {points: 10, all: {cm_TT: 15}}
Onto Easy Street:
  - {points: -10, all: {cm_EZ: 64, cm_GG: 52}}
  - {points: 10, all: {cm_EZ: 64}}
  - {points: 5, all: {cm_GG: 52}}
Bad SUPP 64:
  - {points: -10, all: {cm_M: 43, cm_LL: 21}}
  - {points: 10, all: {cm_LL: 21}}
  - {points: 5, all: {cm_M: 43}}
Ave Doesn't Exist on Signs:
  - {points: 10, all: {cm_EE: 73}}
On Course (CCC 57):
  - {points: 10, all: {cm_CCC: 57}}
Wakeforest not Wake Forest (Don't Split Words):
  - {points: 10, all: {cm_G: 38}}
Op Not Defined:
  - {points: 10, all: {cm_JJJ: 7}}
Misspelled NLORBN in SUPP 7:
  - {points: 10, all: {cm_V: 46}}
Dead End at Roslyn:
  - {points: 5, all: {cm_TTT: 25}}
On Course (RR 61):
  - {points: 10, all: {cm_RR: 61}}
Lane Doesn't Exist on Signs:
  - {points: -10, all: {cm_NN: 40, cm_J: 66}}
  - {points: 10, all: {cm_NN: 40, cm_TTT: 25}}
  - {points: 5, all: {cm_NN: 40}}
  - {points: 7, all: {cm_J: 66}}
North Fernwood is Just Fernwood:
  - {points: 20, all: {cm_PPP: 28, cm_PP: 47}}
  - {points: 10, any: {cm_PPP: 28, cm_PP: 47}}
But W Fernwood is W Fernwood:
  - {points: 15, all: {cm_PPP: 28, cm_PP: 47, cm_UU: 2}}
  - {points: 5, all: {cm_UU: 2}}
RT Undefined:
  - {points: 10, all: {cm_O: 70}}
DR! Undefined:
  - {points: 10, all: {cm_FFF: 56}}
Two Parts (a) in SUPP 56:
  - {points: -10, all: {cm_D: 31, cm_JJ: 62}}
  - {points: 10, all: {cm_D: 31}}
  - {points: 5, all: {cm_JJ: 62}}
Ontwo Not Onto:
  - {points: 10, all: {cm_MM: 5}}
Duplicating Part (c) of SUPP 5:
  - {points: 10, all: {cm_Y: 12}}
DRI Only Deletes One RI 10:
  - {points: -10, all: {cm_H: 50, cm_MMM: 63}}
  - {points: 10, all: {cm_H: 50}}
  - {points: 5, all: {cm_MMM: 63}}
Duane Not Dwayne:
  - {points: -10, all: {cm_AAA: 29, cm_SS: 48}}
  - {points: 10, all: {cm_AAA: 29}}
  - {points: 5, all: {cm_SS: 48}}
Execute a Second RI 13:
  - {points: -10, all: {cm_HHH: 10, cm_IL: 77}}
  - {points: 10, all: {cm_HHH: 10}}
  - {points: 5, all: {cm_IL: 77}}
DRI Only Deletes One RI 14:
  - {points: 0, all: {cm_HHH: 10, cm_IL: 77, cm_KK: 27}} # already scored -10 above
  - {points: -10, all: {cm_IL: 77, cm_KK: 27}}
  - {points: 10, all: {cm_KK: 27}}
Dead End at Eureka:
  - {points: 5, all: {cm_GGG: 59}}
Still Repeating R and L at SUPP 59:
  - {points: -10, all: {cm_CA: 72, cm_GGG: ""}}
  - {points: 10, all: {cm_CA: 72, cm_GGG: 59}}
U to Stay Onto Before SP (Unscored):
  - {points: 0, all: {cm_XX: 17}}
First SP:
  - {points: 100, all: {CP_1: True}}
Correctly Started the Seance:
  - {points: 10, all: {CP_3: True}}
Knocked on Dashboard:
  - {points: 10, all: {CP_8: True}}
Upholstery Color:
  - {points: 10, all: {CP_4: True}}
Asked the Spirits How You Will Place:
  - {points: 10, all: {CP_9: True}}
All Signs Say Yes:
  - {points: 15, all: {CP_5: True}}
  - {points: 30, all: {CP_12: True}}
Hemlock Sign Removed so Street Unnamed:
  - {points: 25, all: {cm_OOO: 22, cm_NV: 71, cm_FF: "", cm_LLL: ""}}
  - {points: -10, all: {cm_LLL: 41, cm_OOO: 22}}
  - {points: -10, all: {cm_LLL: 41, cm_NV: 71}}
  - {points: 5, all: {cm_FF: 3, cm_LLL: 41}}
  - {points: 5, all: {cm_FF: 3, cm_OOO: 22}}
  - {points: 5, all: {cm_FF: 3, cm_NV: 71}}
  - {points: 15, all: {cm_OOO: 22}}
  - {points: 10, all: {cm_LLL: 41}}
  - {points: 5, all: {cm_NV: 71}}
  - {points: 2, all: {cm_FF: 3}}
Dead End at Madrone (Unscored):
  - {points: 0, all: {cm_CC: 55}}
Dead End at Arriba:
  - {points: 5, all: {cm_DDD: 33}}
Turn for Dead End at Acalanes so Not Onto:
  - {points: 0, multi: {cm_T: 26, cm_OO: 54, cm_HH: 35}}
  - {points: 5, all: {cm_HH: 35}}
  - {points: 5, all: {cm_OO: 54}}
  - {points: 10, all: {cm_T: 26}}
Lagging RIs 17-20:
  - {points: -10, all: {cm_QQ: 44, cm_HH: 35}}
  - {points: -10, all: {cm_QQ: 44, cm_OO: 54}}
  - {points: -10, all: {cm_Q: 11, cm_HH: 35}}
  - {points: -10, all: {cm_Q: 11, cm_OO: 54}}
  - {points: 20, all: {cm_T: 26, cm_Q: 11, cm_QQ: 44}}
  - {points: -10, all: {cm_QQ: 44}}
  - {points: 5, all: {cm_T: 26, cm_Q: 11}}
  - {points: 0, all: {cm_Q: 11}}
Everything Following 'at' (Carson and Leota):
  - {points: 10, all: {cm_K: 9}}
On Course (W is on Signs):
  - {points: 0, all: {cm_W: 8, cm_S: 36}}
  - {points: 10, all: {cm_W: 8, cm_S: ""}}
Ignore McKinley When Counting Chances:
  - {points: 10, all: {cm_AA: 16}}
Bad Dead End at Vasquez and Vasquez:
  - {points: -5, all: {cm_II: 23}}
RIs Only Have One Part:
  - {points: 0, all: {cm_B: 18, cm_S: 36}}
  - {points: 5, all: {cm_S: 36}}
  - {points: 10, all: {cm_B: 18}}
On Course (Z 19):
  - {points: 10, all: {cm_Z: 19}}
SUPP 19 Deleted Uncompleted Parts of SUPP 18 (or 36):
  - {points: 15, all: {cm_BBB: 6}}
Swapping L and R at L 78:
  - {points: 20, all: {cm_BBB: 6, cm_R: 78, cm_L: 78}}
  - {points: 10, all: {cm_R: 78, cm_L: 78}}
  - {points: 10, all: {cm_BBB: 6, cm_L: 78}}
  - {points: 5, all: {cm_BBB: 6, cm_R: 78}}
  - {points: 5, all: {cm_R: 78}}
  - {points: 0, all: {cm_L: 78}}
Swap R and L in RI 24:
  - {points: 10, all: {cm_DD: 24}}
SUPP 24 Part (l) is (r):
  - {points: -10, all: {cm_GM: 74, cm_AB: 67}}
  - {points: -10, all: {cm_GM: 74, cm_GC: 80}}
  - {points: -10, all: {cm_GM: 74, cm_DD: ""}}
  - {points: 10, all: {cm_GC: 80, cm_AB: 67}}
  - {points: 3, all: {cm_GC: 80}}
  - {points: 6, all: {cm_AB: 67}}
  - {points: 20, all: {cm_GM: 74}}
Sutter Not Stutter (also R at Uninstructed T):
  - {points: -10, all: {cm_F: 1, cm_X: 30}}
  - {points: -10, all: {cm_F: 1, cm_I: 45}}
  - {points: -10, all: {cm_MT: 34, cm_X: 30}}
  - {points: -10, all: {cm_MT: 34, cm_I: 45}}
  - {points: 20, all: {cm_F: 1, cm_MT: 34}}
  - {points: 10, all: {cm_F: 1}}
  - {points: 15, all: {cm_X: 30, cm_I: 45}}
  - {points: 5, all: {cm_X: 30}}
Still Ignoring McKinley:
  - {points: 20, all: {cm_U: 14, cm_RRR: 49}}
  - {points: 10, any: {cm_U: 14, cm_RRR: 49}}
Way Doesn't Exist on Signs:
  - {points: 10, all: {cm_WW: 32}}
Logos Also Don't Exist on Signs:
  - {points: 10, all: {cm_EEE: 4}}
On Course (QQQ 39):
  - {points: 10, all: {cm_QQQ: 39}}
Sallie Not Sara (Also Seance Medium Instruction):
  - {points: -10, multi: {cm_C: 13, cm_NNN: 42, cm_UUU: 58, cm_III: 51}}
  - {points: 20, all: {cm_C: 13}}
  - {points: 15, multi: {cm_NNN: 42}}
  - {points: 10, multi: {cm_UUU: 58}}
  - {points: 5, multi: {cm_III: 51}}
Executed RIs (Should Only be 13):
  - {points: 5, all: {CP_7: True}}
  - {points: 8, all: {CP_14: True}}
  - {points: 13, all: {CP_13: True}}
Driver is Fred Larsen:
  - {points: 10, all: {driver_larsen: True}}
Finishing the Rallye:
  - {points: 267, all: {Finished: True}}
FISH - SSS 53:
  - {points: -20, all: {cm_SSS: 53}}
FISH - VV 60:
  - {points: -20, all: {cm_VV: 60}}
FISH - A 68:
  - {points: -20, all: {cm_A: 68}}
FISH - N 75:
  - {points: -20, all: {cm_N: 75}}
FISH - WWW 65:
  - {points: -20, all: {cm_WWW: 65}}


